stages:
  - containerization
  - deploy

variables:
  KUBERNETES_NAMESPACE: moreillon
  CONTAINER_REGISTRY: 192.168.1.2:5000
  APPLICATION_NAME: finances
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}


containerization:
  stage: containerization
  script:
    - cp ${ENV} ./.env
    - cp ${SECRETS} ./secrets.js
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
